# Generated by Django 4.1.1 on 2023-02-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonemojis",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="Name"),
        ),
    ]
