# Generated by Django 4.2.5 on 2023-10-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0006_rename_emoji_embed_embed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('chance', models.PositiveIntegerField(verbose_name='Chance')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
