# Generated by Django 3.2.7 on 2021-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20211007_0005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
