# Generated by Django 4.1 on 2023-01-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_era_group_idol_remove_card_cardname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="idol",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="base.idol",
            ),
        ),
    ]
