# Generated by Django 4.1 on 2022-09-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_card_image1_alter_card_image2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimeSeries',
            new_name='GroupName',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='series',
            new_name='group',
        ),
    ]
