# Generated by Django 4.1 on 2023-01-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_card_idol"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="emoji",
            field=models.CharField(default="", max_length=64, verbose_name="Emoji"),
        ),
        migrations.AlterField(
            model_name="card",
            name="era",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="base.era",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="base.group",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="base.rarity",
            ),
        ),
    ]
