# Generated by Django 4.1 on 2023-01-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_group_emoji_alter_card_era_alter_card_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="era",
            name="short",
            field=models.CharField(
                default="", max_length=8, verbose_name="ShortName"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="short",
            field=models.CharField(
                default="", max_length=8, verbose_name="ShortName"
            ),
        ),
        migrations.AddField(
            model_name="idol",
            name="short",
            field=models.CharField(
                default="", max_length=8, verbose_name="ShortName"
            ),
        ),
    ]
