# Generated by Django 4.1 on 2023-01-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_era_short_group_short_idol_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="era",
            name="short",
            field=models.CharField(default="", max_length=8, verbose_name="ShortName"),
        ),
        migrations.AlterField(
            model_name="group",
            name="short",
            field=models.CharField(default="", max_length=8, verbose_name="ShortName"),
        ),
        migrations.AlterField(
            model_name="idol",
            name="short",
            field=models.CharField(default="", max_length=8, verbose_name="ShortName"),
        ),
    ]
