# Generated by Django 4.1 on 2023-01-25 21:29

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_era_short_alter_group_short_alter_idol_short"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="image6",
        ),
        migrations.RemoveField(
            model_name="card",
            name="image7",
        ),
        migrations.RemoveField(
            model_name="card",
            name="image8",
        ),
        migrations.RemoveField(
            model_name="card",
            name="levels",
        ),
        migrations.AddField(
            model_name="rarity",
            name="levels",
            field=models.CharField(
                default="1,4,10,25,50",
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="emoji",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Emoji"
            ),
        ),
        migrations.AlterField(
            model_name="rarity",
            name="emoji",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
