# Generated by Django 4.1.1 on 2023-01-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_commonemojis"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommonEmojis",
        ),
    ]
