# Generated by Django 4.1.1 on 2023-02-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_delete_commonemojis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="card",
            name="image5",
        ),
        migrations.RemoveField(
            model_name="card",
            name="rarity",
        ),
        migrations.AddField(
            model_name="inventory",
            name="cardUID",
            field=models.CharField(
                editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
