# Generated by Django 4.1.1 on 2023-02-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_remove_card_image4_remove_card_image5_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="count",
            new_name="xp",
        ),
        migrations.RemoveField(
            model_name="rarity",
            name="levels",
        ),
        migrations.AddField(
            model_name="rarity",
            name="level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
