# Generated by Django 4.1.1 on 2023-02-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_rename_count_inventory_xp_remove_rarity_levels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="current_index",
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
