# Generated by Django 4.1.1 on 2023-02-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_card_current_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="current_index",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
