# Generated by Django 4.1.1 on 2023-02-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_card_current_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="balance",
            new_name="carrots",
        ),
    ]
