# Generated by Django 4.2.5 on 2023-09-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_rename_balance_player_carrots"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="emoji",
        ),
    ]
