# Generated by Django 4.2.5 on 2023-09-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_remove_group_emoji"),
    ]

    operations = []
