# Generated by Django 4.2.5 on 2023-09-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_merge_0013_commonemojis_0020_remove_group_emoji"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cooldowns",
            new_name="Cooldown",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="image1",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="card",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="card",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="xp",
        ),
        migrations.RemoveField(
            model_name="rarity",
            name="level",
        ),
        migrations.AddField(
            model_name="card",
            name="rarity",
            field=models.ForeignKey(
                null=True,
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="base.rarity",
            ),
        ),
    ]
