# Generated by Django 4.2.5 on 2023-09-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_rename_cooldowns_cooldown_delete_commonemojis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="base.rarity",
            ),
        ),
    ]
