# Generated by Django 4.2.5 on 2023-09-30 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_delete_commonemojis_alter_card_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEraCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, editable=False)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.era')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player')),
            ],
        ),
    ]
