# Generated by Django 4.2.5 on 2023-10-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_delete_commonemojis'),
        ('base', '0025_delete_commonemojis_cooldown_lastdiscover_and_more'),
    ]

    operations = [
    ]
