# Generated by Django 4.2.5 on 2023-11-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_merge_20231022_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='userID',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='User Id'),
        ),
    ]
